name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        REFRESH_SECRET: ${{ secrets.REFRESH_SECRET }}
      run: go test -v ./api/...
